#!/bin/bash

# Set Firefox homepage to http://domserver.cosc.canterbury.ac.nz/domjudge/team/
cat << EOF_FIREPREFS > /usr/lib/firefox/defaults/pref/all.corp.js
lockPref("browser.startup.homepage","http://dmjappprd01.sit.auckland.ac.nz/domjudge/team/");
EOF_FIREPREFS

# Setup IPTABLES to block all internet traffic, except the DOMJudge servers and IP printers
iptables -F
iptables -P INPUT DROP
iptables -P FORWARD ACCEPT
iptables -P OUTPUT DROP
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -d 132.181.7.114/32 -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -d 130.216.8.43/32 -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 631 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 631 -j ACCEPT

# UWA-specific printer setup
if [ -n "`ifconfig eth0 | grep 130.95`" ]; then
	# Install ppd
	wget -O /etc/cups/ppd/205.ppd https://raw.githubusercontent.com/N-Yuki/sppc-ubuntu-customisation/master/remote/uwa-205.ppd
	# Setup UWA printers
	cat << EOF_PRINTER > /etc/cups/printers.conf
	# Printer configuration file for CUPS v1.7.2
	# Written by cupsd
	# DO NOT EDIT THIS FILE WHEN CUPSD IS RUNNING
	<DefaultPrinter 205>
	UUID urn:uuid:6d6b9a28-750b-3713-5352-627c5f213590
	Info HP LaserJet 4350
	Location Lab 2.05
	DeviceURI ipp://130.95.116.32
	PPDTimeStamp *
	State Idle
	StateTime 1439606521
	Type 8425668
	Accepting Yes
	Shared Yes
	ColorManaged Yes
	JobSheets none none
	QuotaPeriod 0
	PageLimit 0
	KLimit 0
	OpPolicy default
	ErrorPolicy retry-job
	</Printer>
	EOF_PRINTER
fi

# Remove sudo access
rm -fr /etc/sudoers.d
sed -r -i '/%admin|%sudo/ s/^/#/' /etc/sudoers
